#!/usr/bin/env python
"""
Verify that Celery-encoded videos are properly synced to Supabase content_media table.
This helps debug the issue where Flutter app can't find videos after encoding.
"""

import os
import django
from django.conf import settings

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ott_backend.settings')
django.setup()

from django.db import connection
from hls_streaming.models import Video, HLSPlaylist
from supabase import create_client

def check_django_videos():
    """Check videos in Django HLS database"""
    print("\n" + "="*80)
    print("📊 DJANGO HLS DATABASE (Video Encoding Tracking)")
    print("="*80)
    
    videos = Video.objects.all().order_by('-created_at')[:5]
    
    if not videos:
        print("❌ No videos found in Django database")
        return
    
    print(f"✅ Found {videos.count()} recent videos:\n")
    
    for video in videos:
        print(f"  Video ID: {video.id}")
        print(f"  Title: {video.title}")
        print(f"  Status: {video.status}")
        
        # Check HLS Playlist
        hls = HLSPlaylist.objects.filter(video=video).first()
        if hls:
            print(f"  HLS Status: {hls.status}")
            print(f"  Master URL: {hls.master_playlist_url}")
            print(f"  R2 Uploaded: {hls.r2_uploaded}")
        else:
            print(f"  ⚠️  No HLS playlist found!")
        print()


def check_app_supabase():
    """Check content_media entries in App Supabase database"""
    print("\n" + "="*80)
    print("🎯 APP SUPABASE DATABASE (Flutter App Reads From Here)")
    print("="*80)
    
    supabase_url = os.getenv('SUPABASE_URL')
    supabase_key = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
    
    if not supabase_url or not supabase_key:
        print("❌ Supabase credentials not found!")
        print(f"   SUPABASE_URL: {supabase_url}")
        print(f"   SUPABASE_SERVICE_ROLE_KEY: {'NOT SET' if not supabase_key else '***'}")
        return
    
    try:
        supabase = create_client(supabase_url, supabase_key)
        print(f"✅ Connected to: {supabase_url}")
        
        # Fetch recent content_media entries with video type
        print("\n📋 Recent video entries in content_media table:")
        response = supabase.table('content_media').select('*').eq('media_type', 'video').order('created_at', desc=True).limit(10).execute()
        
        if not response.data:
            print("❌ No video entries found in content_media!")
            return
        
        print(f"✅ Found {len(response.data)} video entries:\n")
        
        for entry in response.data:
            content_id = entry.get('content_id', 'N/A')
            file_url = entry.get('file_url', 'N/A')
            created_at = entry.get('created_at', 'N/A')
            
            # Check if file_url is an HLS master.m3u8
            is_hls = 'master.m3u8' in file_url if file_url else False
            hls_indicator = "✅ HLS" if is_hls else "⚠️  Non-HLS"
            
            print(f"  [{hls_indicator}] Content ID: {content_id}")
            print(f"     URL: {file_url[:80]}{'...' if len(file_url) > 80 else ''}")
            print(f"     Created: {created_at}")
            print()
        
    except Exception as e:
        print(f"❌ Error connecting to Supabase: {str(e)}")


def check_mismatch():
    """Check for mismatches between Django videos and Supabase entries"""
    print("\n" + "="*80)
    print("🔍 MISMATCH ANALYSIS")
    print("="*80)
    
    supabase_url = os.getenv('SUPABASE_URL')
    supabase_key = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
    
    if not supabase_url or not supabase_key:
        print("❌ Cannot check: Supabase credentials not found")
        return
    
    try:
        supabase = create_client(supabase_url, supabase_key)
        
        # Get recent videos from Django
        django_videos = Video.objects.filter(status='completed').order_by('-created_at')[:5]
        
        if not django_videos:
            print("ℹ️  No completed videos in Django to analyze")
            return
        
        print(f"Checking {django_videos.count()} completed videos...\n")
        
        for video in django_videos:
            # Get HLS playlist
            hls = HLSPlaylist.objects.filter(video=video).first()
            if not hls or not hls.master_playlist_url:
                print(f"❌ {video.id}: No HLS master URL found")
                continue
            
            # Generate expected content_id patterns
            expected_ids = [
                f'content_{video.id}',  # Generated by Celery if no content_id passed
                # Add more patterns as needed based on admin portal naming
            ]
            
            # Check if any content_media entry has this master.m3u8 URL
            master_url = hls.master_playlist_url
            
            found = False
            for content_id in expected_ids:
                response = supabase.table('content_media').select('*').eq('content_id', content_id).eq('media_type', 'video').execute()
                
                if response.data:
                    for entry in response.data:
                        if entry.get('file_url') == master_url:
                            print(f"✅ {video.id}: FOUND in content_media")
                            print(f"   Content ID: {content_id}")
                            print(f"   Master URL: {master_url}")
                            found = True
                            break
            
            if not found:
                print(f"❌ {video.id}: NOT FOUND in content_media")
                print(f"   Video Title: {video.title}")
                print(f"   Master URL: {master_url}")
                print(f"   Expected content_id: {expected_ids[0]}")
                print(f"   Action: Check Celery logs for errors or re-encode this video")
            print()
        
    except Exception as e:
        print(f"❌ Error during mismatch check: {str(e)}")


def main():
    print("\n" + "#"*80)
    print("# 🔧 CONTENT MEDIA SYNC VERIFICATION")
    print("# Checks if Celery-encoded videos are properly saved to Supabase")
    print("#"*80)
    
    check_django_videos()
    check_app_supabase()
    check_mismatch()
    
    print("\n" + "#"*80)
    print("# ✅ Verification Complete")
    print("#"*80 + "\n")


if __name__ == '__main__':
    main()
