# Generated by Django 4.2 on 2026-02-25 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HLSPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('encoding', 'Encoding'), ('uploading', 'Uploading to R2'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('master_playlist_url', models.URLField(blank=True, max_length=500)),
                ('master_playlist_local_path', models.CharField(blank=True, max_length=500)),
                ('r2_prefix', models.CharField(blank=True, max_length=255)),
                ('r2_uploaded', models.BooleanField(default=False)),
                ('renditions_data', models.JSONField(default=dict)),
                ('estimated_size_mb', models.FloatField(blank=True, null=True)),
                ('primary_codec', models.CharField(choices=[('h265', 'H.265'), ('h264', 'H.264')], default='h265', max_length=20)),
                ('fallback_codec', models.CharField(choices=[('h265', 'H.265'), ('h264', 'H.264')], default='h264', max_length=20)),
                ('segment_duration', models.IntegerField(default=6)),
                ('segment_count', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('encoding_started_at', models.DateTimeField(blank=True, null=True)),
                ('encoding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_file', models.FileField(upload_to='uploads/originals/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('encoding', 'Encoding'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HLSSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendition', models.CharField(max_length=50)),
                ('segment_number', models.IntegerField()),
                ('duration_seconds', models.FloatField()),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hls_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='hls_streaming.hlsplaylist')),
            ],
            options={
                'ordering': ['rendition', 'segment_number'],
            },
        ),
        migrations.AddField(
            model_name='hlsplaylist',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hls_playlist', to='hls_streaming.video'),
        ),
        migrations.AddIndex(
            model_name='hlssegment',
            index=models.Index(fields=['hls_playlist', 'rendition'], name='hls_streami_hls_pla_3560d4_idx'),
        ),
        migrations.AddIndex(
            model_name='hlsplaylist',
            index=models.Index(fields=['status'], name='hls_streami_status_bb81b4_idx'),
        ),
        migrations.AddIndex(
            model_name='hlsplaylist',
            index=models.Index(fields=['video'], name='hls_streami_video_i_94363a_idx'),
        ),
    ]
