# Generated by Django 4.2 on 2026-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hls_streaming', '0002_alter_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hlsplaylist',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
