# Generated by Django 4.2 on 2026-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hls_streaming', '0003_hlsplaylist_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hlsplaylist',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hlsplaylist',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('encoding', 'Encoding'), ('uploading', 'Uploading to R2'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
